from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditWindow(object):
    def setupUi(self, EditWindow):
        EditWindow.setObjectName("EditWindow")
        EditWindow.resize(700, 553)
        self.centralwidget = QtWidgets.QWidget(EditWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setMinimumSize(QtCore.QSize(700, 500))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(5, 0, 171, 531))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.toolsLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.toolsLayout.setContentsMargins(0, 0, 0, 0)
        self.toolsLayout.setObjectName("toolsLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.btn_save = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_save.setObjectName("btn_save")
        self.verticalLayout_2.addWidget(self.btn_save)
        self.btn_export = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_export.setObjectName("btn_export")
        self.verticalLayout_2.addWidget(self.btn_export)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem)
        self.toolsLayout.addLayout(self.verticalLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.btn_pipette = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_pipette.sizePolicy().hasHeightForWidth())
        self.btn_pipette.setSizePolicy(sizePolicy)
        self.btn_pipette.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_pipette.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_pipette.setCheckable(True)
        self.btn_pipette.setObjectName("btn_pipette")
        self.toolsButtons = QtWidgets.QButtonGroup(EditWindow)
        self.toolsButtons.setObjectName("toolsButtons")
        self.toolsButtons.addButton(self.btn_pipette)
        self.gridLayout.addWidget(self.btn_pipette, 1, 0, 1, 1)
        self.btn_pen = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_pen.sizePolicy().hasHeightForWidth())
        self.btn_pen.setSizePolicy(sizePolicy)
        self.btn_pen.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_pen.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_pen.setCheckable(True)
        self.btn_pen.setChecked(True)
        self.btn_pen.setAutoExclusive(False)
        self.btn_pen.setAutoDefault(False)
        self.btn_pen.setDefault(False)
        self.btn_pen.setObjectName("btn_pen")
        self.toolsButtons.addButton(self.btn_pen)
        self.gridLayout.addWidget(self.btn_pen, 0, 0, 1, 1)
        self.btn_eraser = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_eraser.sizePolicy().hasHeightForWidth())
        self.btn_eraser.setSizePolicy(sizePolicy)
        self.btn_eraser.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_eraser.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_eraser.setCheckable(True)
        self.btn_eraser.setObjectName("btn_eraser")
        self.toolsButtons.addButton(self.btn_eraser)
        self.gridLayout.addWidget(self.btn_eraser, 0, 1, 1, 1)
        self.toolsLayout.addLayout(self.gridLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.toolsLayout.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_turnGrid = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_turnGrid.setObjectName("btn_turnGrid")
        self.horizontalLayout_2.addWidget(self.btn_turnGrid)
        self.btn_gridColorChange = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_gridColorChange.setObjectName("btn_gridColorChange")
        self.horizontalLayout_2.addWidget(self.btn_gridColorChange)
        self.toolsLayout.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.toolsLayout.addItem(spacerItem2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.slider_scaleEdit = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.slider_scaleEdit.setMinimum(0)
        self.slider_scaleEdit.setMaximum(100)
        self.slider_scaleEdit.setPageStep(1)
        self.slider_scaleEdit.setProperty("value", 0)
        self.slider_scaleEdit.setOrientation(QtCore.Qt.Horizontal)
        self.slider_scaleEdit.setObjectName("slider_scaleEdit")
        self.verticalLayout.addWidget(self.slider_scaleEdit)
        self.toolsLayout.addLayout(self.verticalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.toolsLayout.addItem(spacerItem3)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.toolsLayout.addLayout(self.gridLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_colorChange = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_colorChange.setMinimumSize(QtCore.QSize(51, 51))
        self.btn_colorChange.setMaximumSize(QtCore.QSize(51, 51))
        self.btn_colorChange.setText("")
        self.btn_colorChange.setObjectName("btn_colorChange")
        self.horizontalLayout.addWidget(self.btn_colorChange)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.toolsLayout.addLayout(self.verticalLayout_3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.toolsLayout.addItem(spacerItem4)
        self.canvas = QtWidgets.QLabel(self.centralwidget)
        self.canvas.setGeometry(QtCore.QRect(180, 10, 500, 500))
        self.canvas.setMinimumSize(QtCore.QSize(500, 300))
        self.canvas.setMouseTracking(True)
        self.canvas.setText("")
        self.canvas.setObjectName("canvas")
        EditWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(EditWindow)
        self.statusbar.setObjectName("statusbar")
        EditWindow.setStatusBar(self.statusbar)

        self.retranslateUi(EditWindow)
        QtCore.QMetaObject.connectSlotsByName(EditWindow)

    def retranslateUi(self, EditWindow):
        _translate = QtCore.QCoreApplication.translate
        EditWindow.setWindowTitle(_translate("EditWindow", "EditWindow"))
        self.pushButton.setText(_translate("EditWindow", "New project"))
        self.btn_save.setText(_translate("EditWindow", "Save"))
        self.btn_export.setText(_translate("EditWindow", "Export"))
        self.btn_pipette.setText(_translate("EditWindow", "Pipette"))
        self.btn_pen.setText(_translate("EditWindow", "Pen"))
        self.btn_eraser.setText(_translate("EditWindow", "Eraser"))
        self.btn_turnGrid.setText(_translate("EditWindow", "grid"))
        self.btn_gridColorChange.setText(_translate("EditWindow", "gridColor"))
        self.label.setText(_translate("EditWindow", "Scale"))

class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(239, 113)
        dialog.setMinimumSize(QtCore.QSize(239, 113))
        dialog.setMaximumSize(QtCore.QSize(239, 113))
        self.formLayoutWidget = QtWidgets.QWidget(dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 221, 61))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.widthEdit = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.widthEdit.setObjectName("widthEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.widthEdit)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.heightEdit = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.heightEdit.setObjectName("heightEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.heightEdit)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_2.setScaledContents(False)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.btn_create = QtWidgets.QPushButton(dialog)
        self.btn_create.setGeometry(QtCore.QRect(20, 80, 75, 23))
        self.btn_create.setObjectName("btn_create")
        self.btn_open = QtWidgets.QPushButton(dialog)
        self.btn_open.setGeometry(QtCore.QRect(130, 80, 75, 23))
        self.btn_open.setObjectName("btn_open")
        self.label_3 = QtWidgets.QLabel(dialog)
        self.label_3.setGeometry(QtCore.QRect(110, 80, 21, 21))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "NewProject"))
        self.label.setText(_translate("dialog", "width"))
        self.label_2.setText(_translate("dialog", "height"))
        self.btn_create.setText(_translate("dialog", "Create"))
        self.btn_open.setText(_translate("dialog", "Open"))
        self.label_3.setText(_translate("dialog", "or"))
